apiVersion: v1
kind: pod
metadata:
    name: docker-image-build
spec:
    containers:
    -   name: ez-docker-helm-build
        image: ezezeasy/ez-docker-helm-build:1.41
        imagePullPolicy: Always
        securityContext:
            privileged: true

