apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.py" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app.py" . }}
  template:
    metadata:
      labels:
        app: {{ include "app.py" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongoSecret.name }}
                  key: mongo-uri
